<?php include_once($this->getViewPath('template/header.phtml'));?>
<main>
<br>
<div class="row container">
<div class="col offset-m4 s12 m4">
    <div class="card horizontal">
      <div class="card-image">
      <img src="<?php echo '/resources/images/'.$_SESSION['user_image']; ?>">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p><?php echo $_SESSION['user_email']; ?></p>
        </div>
      </div>
    </div>
  </div>
  </div>
<div class="row container">
<form action="/users/upload" method="POST" enctype="multipart/form-data">
    <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <input type="file" name="file" id="file" required>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <input type="hidden" name="token" value="<?php isset($_COOKIE['token'])? print($_COOKIE['token']):''?>">
    <button class="btn waves-effect waves-light" type="submit">Upload</button>
</form>

</div>
</main>
<?php include_once($this->getViewPath('template/footer.phtml'));?>
