<div class="row">
    <input placeholder="Name" type="text" name="name" class="validate" value="<?php isset($product)? print($product->getName()):''?>"/>
</div>
<div class="row">
    <input type="text" placeholder="price" class="validate" name="price" value="<?php isset($product)? print($product->getPrice()):''?>"/>
</div>
<div class="row">

<input type="hidden" name="token" value="<?php isset($_COOKIE['token'])? print($_COOKIE['token']):''?>">
</div>