<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	  <link rel="stylesheet" href="/resources/assets/materialize.min.css">
    <link rel="stylesheet" href="/resources/assets/main.css">
    <title>Products</title>
</head>
<body>
<nav>
    <div class="nav-wrapper green">
      <a href="/" class="brand-logo center">App</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/users/signin">login</a></li>
      </ul>
    </div>
</nav>
<main>
<div class="container-center">
<div class="row valign-wrapper">
            <div class="col s12">
                <div class="card white hoverable">
                    <div class="card-content">
                        <span class="card-title">Register</span>
                        <div>
                            <form method="post" action="/users/register">
                                <label for="email" class="">Email</label>
                                <input id="email" class="" type="text" name="email"/>
                                <label for="password" class="">Password</label>
                                <input id="password" class="" type="password" name="password"/>
                                <input class="btn btn-large green" type="submit" value="Start"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<footer class="page-footer green">
    <div class="footer-copyright">
        <div class="container">
            © Company
            <a class="grey-text text-lighten-4 right" href="/">about</a>
        </div>
    </div>
</footer>
<script src="/resources/assets/materialize.min.js"></script>
</body>
</html>