<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="/resources/assets/materialize.min.css">
    <link rel="stylesheet" href="/resources/assets/main.css">
    <title>Products</title>
</head>
<?php session_start(); ?>
<body>
<nav>
    <div class="nav-wrapper green">
      <a href="/" class="brand-logo center">App</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li>
            <form action="/" method="GET">
              <div class="input-field">
                <input id="search" name="search" type="search" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
              </div>
            </form>
          </li>
      </ul>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <?php if(isset($_SESSION['user_email'])):?>
            <li>
              <a href="/users/image" onclick="event.preventDefault(); document.getElementById('profile-form').submit();">profile</a>
              <form id="profile-form" action="/users/image" method="POST">
                <input type="hidden" name="token" value="<?php isset($_COOKIE['token'])? print($_COOKIE['token']):''?>">
              </form>  
            </li>
            <li>
              <a href="/users/logout" class="btn-small btn-floating red" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="material-icons">power_settings_new</i></a>    
              <form id="logout-form"  action="/users/logout" method="POST">
                <input type="hidden" name="token" value="<?php isset($_COOKIE['token'])? print($_COOKIE['token']):''?>">
              </form>
            </li>
          <?php else: ?>
            <li><a href="/users/signin">login</a></li>
            <li><a href="/users/signup">register</a></li>
          <?php endif ?>
      </ul>
    </div>
  </nav>
